name: Pre-Staging Review Accessibility Testing
description: Complete required Foundational Testing prior to your Staging Review
title: "[Bug]: [Insert Product Name]"
labels: ["a11y-foundational-testing"]
assignees:
  - briandeconinck
body:
  - type: markdown
    attributes:
      value: |
        ## Introduction
  - type: markdown
    attributes:
      value: |
        Instructions up here referencing [Platform website testing info](https://depo-platform-documentation.scrollhelp.site/developer-docs/prepare-for-an-accessibility-staging-review) and how to get help from Shared Support.
  - type: markdown
    attributes:
      value: |
        ## Keyboard navigation
  - type: markdown
    attributes:
      value: |
        All pages and user flows (forms, data entry, navigation, user interface, etc.) must be navigable using a keyboard. To test keyboard navigation, press [Tab] to move focus to the next element that can receive keyboard focus and [Shift] + [Tab] to move focus to the previous element. [Learn more about keyboard navigation testing](https://depo-platform-documentation.scrollhelp.site/developer-docs/prepare-for-an-accessibility-staging-review#Keyboard-navigation-check) or [watch a keyboard navigation testing demo](https://www.youtube.com/watch?v=YvPEK1Y08uM).
  - type: input
    id: keyboard-tester
    attributes:
      label: Who completed the keyboard navigation test?
      description: Enter their GitHub username to tag them in this ticket.
  - type: checkboxes
    id: keyboard-checks
    attributes:
      label: Keyboard navigation checks
      options:
        - label: Each link, button, form input, checkbox, radio button, select menu, and custom element can receive keyboard focus
        - label: All elements under focus have a visible focus indicator
        - label: The order of [Tab] stops made sense and was appropriate for completing tasks
  - type: textarea
    id: keyboard-notes
    attributes:
      label: How did it go?
      description: Do you have any questions or notes? Is there anything you want someone to look at before Staging Review? Be sure to reference any GitHub issues you've created as a result of this testing!
  - type: markdown
    attributes:
      value: |
        ## Color contrast
  - type: markdown
    attributes:
      value: |
        ... and so on, for each part of Foundational testing.
